---

- name: Create a new subnet in Azure
  azure_rm_subnet:

    # Subnet details
    name: "{{ azure_snet_name }}"
    resource_group: "{{ azure_rg_name }}"
    virtual_network_name: "{{ azure_vnet_name }}"
    address_prefix_cidr: "{{ net_prefix }}"
    tags:
      app_name: "{{ app_name }}"
      app_tier: "{{ app_tier }}"
      app_env: "{{ app_env }}"
      billing_id: "{{ billing_id }}"
      business_unit: "{{ business_unit }}"
      support_group: "{{ support_group }}"

    # NSG details
    security_group:
      name: "{{ azure_nsg_name }}"
      resource_group: "{{ azure_rg_name }}"

...