---

- name: Add next prefix in Netbox
  netbox.netbox.netbox_prefix:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:

      # Define criteria for prefix
      parent: "{{ prefix_parent }}"
      prefix_length: "{{ prefix_length }}"

      # Define criteria for site
      tenant: "{{ tenant_name }}"
      site: "{{ azure_location }}"

      # Metadata
      prefix_role: "{{ prefix_role }}"
      description: "{{ prefix_desc }}"

      # Tags
      tags:
        - "{{ app_name }}"
        - "{{ app_tier }}"
        - "{{ app_env }}"
        - "{{ billing_id }}"
        - "{{ business_unit }}"
        - "{{ support_group }}"

    # State
    state: present
    first_available: yes

  # Register output
  register: first_available

  # Set stat for prefix string
- name: Set stats
  set_stats:
    data:
      net_prefix: "{{ first_available.prefix.prefix }}"
  
...
